/**
 * Runtime environment configuration.
 * In Docker, values are injected via env-config.js (generated by docker-entrypoint.sh).
 * Falls back to sandbox defaults for local development.
 */

const windowEnv: Record<string, string> = (window as any).__env || {};

export const environment = {
  apiUrl: windowEnv['API_URL'] || '',
  apiAppId: windowEnv['API_APP_ID'] || '',
  apiKey: windowEnv['API_KEY'] || '',
  flightsApiUrl: windowEnv['FLIGHTS_API_URL'] || '',
};
