import { IConfig, IFlight, IPassenger, TSeatAvailability } from '@kwiket/jets-seatmap-angular-lib';
import { environment } from '../environments/environment';

export interface DemoFlight {
  key: string;
  label: string;
  route: string;
  date: string;
  flight: IFlight;
  config: IConfig;
  availability?: TSeatAvailability;
  passengers?: IPassenger[];
}

/** Cabin theme — matches React demo (config-mock.js) visual style */
const CABIN_THEME = {
  seatmapBackgroundColor: '#fff',
  floorColor: '#595959',
  seatStrokeColor: 'rgb(230, 230, 230)',
  seatArmrestColor: '#cccccc',
  armrestColor: '#cccccc',
  seatUnavailableColor: 'dimgrey',
  notAvailableSeatsColor: 'dimgrey',
  bulkBaseColor: 'dimgrey',
  bulkCutColor: 'lightgrey',
  bulkIconColor: 'darkslategray',
  fuselageFillColor: 'lightgrey',
  fuselageStrokeColor: 'darkgrey',
  fuselageWindowsColor: 'darkgrey',
  fuselageWingsColor: 'rgba(55, 55, 55, 0.5)',
  deckLabelTitleColor: 'black',
  wingsWidth: 85,
  cabinTitlesWidth: 85,
};

export const BASE_CONFIG: Omit<IConfig, 'width'> = {
  lang: 'EN',
  apiUrl: environment.apiUrl,
  apiAppId: environment.apiAppId,
  apiKey: environment.apiKey,
  units: 'metric',
  builtInTooltip: true,
  builtInDeckSelector: true,
  singleDeckMode: true,
  visibleFuselage: true,
  visibleSeatPriceLabels: true,
  colorTheme: CABIN_THEME,
};

export const DEMO_FLIGHTS: DemoFlight[] = [
  {
    key: 'qt888',
    label: 'QT888 · LHR → DXB',
    route: 'London → Dubai',
    date: '21 Sep 2026',
    flight: {
      id: 'demo',
      airlineCode: 'QT',
      flightNo: '888',
      departureDate: '2026-09-21',
      departure: 'LHR',
      arrival: 'DXB',
      cabinClass: 'A',
      passengerType: 'ADT',
    },
    config: {
      ...BASE_CONFIG,
      width: 400,
      lang: 'EN',
      horizontal: false,
      rightToLeft: false,
      visibleFuselage: true,
      visibleWings: true,
      visibleCabinTitles: true,
      customCabinTitles: { F: 'First', B: 'Business', P: 'Premium', E: 'Economy' },
      builtInDeckSelector: true,
      singleDeckMode: true,
      builtInTooltip: true,
      externalPassengerManagement: false,
      tooltipOnHover: false,
      scaleType: 'zoom',
      visibleSeatPriceLabels: false,
      colorTheme: {
        seatmapBackgroundColor: '#fff',
        deckLabelTitleColor: 'black',
        deckHeightSpacing: 0,
        wingsWidth: 85,
        deckSeparation: 0,
        floorColor: '#595959',
        seatLabelColor: '#ffffff',
        seatStrokeColor: 'rgb(230, 230, 230)',
        seatStrokeWidth: 1,
        seatArmrestColor: '#cccccc',
        notAvailableSeatsColor: 'dimgrey',
        bulkBaseColor: 'dimgrey',
        bulkCutColor: 'lightgrey',
        bulkIconColor: 'darkslategray',
        defaultPassengerBadgeColor: 'darkred',
        fontFamily: 'Montserrat, sans-serif',
        tooltipBackgroundColor: 'rgb(255,255,255)',
        tooltipHeaderColor: '#4f6f8f',
        tooltipBorderColor: 'rgb(255,255,255)',
        tooltipFontColor: '#4f6f8f',
        tooltipIconColor: '#4f6f8f',
        tooltipIconBorderColor: '#4f6f8f',
        tooltipIconBackgroundColor: '#fff',
        tooltipSelectButtonTextColor: '#fff',
        tooltipSelectButtonBackgroundColor: 'rgb(42, 85, 128)',
        tooltipCancelButtonTextColor: '#fff',
        tooltipCancelButtonBackgroundColor: 'rgb(55, 55, 55)',
        fuselageStrokeWidth: 10,
        fuselageFillColor: 'lightgrey',
        fuselageStrokeColor: 'darkgrey',
        fuselageWindowsColor: 'darkgrey',
        fuselageWingsColor: 'rgba(55, 55, 55, 0.5)',
        fuselageNoseType: 'by-type',
        exitIconUrlLeft: 'https://panorama.quicket.io/icons/exit-left.svg',
        exitIconUrlRight: 'https://panorama.quicket.io/icons/exit-right.svg',
        cabinTitlesWidth: 85,
        customSeatColorRanges: [
          { color: '#c7683d', range: [1, 2.99] },
          { color: '#e6be3f', range: [3, 4.99] },
          { color: '#4071b9', range: [5, 6.5] },
          { color: '#8fb947', range: [6.51, 10] },
        ],
      },
    },
    passengers: [
      { id: 'p1', passengerLabel: 'James Wilson', passengerColor: '#e91e63' },
      { id: 'p2', passengerLabel: 'Emma Clark', passengerColor: '#2196f3' },
    ],
  },
  {
    key: 'ua953',
    label: 'UA953 · ORD → MUC',
    route: 'Chicago → Munich',
    date: '21 Sep 2026',
    flight: {
      id: 'ua953',
      airlineCode: 'UA',
      flightNo: '953',
      departureDate: '2026-09-21',
      departure: 'ORD',
      arrival: 'MUC',
      cabinClass: 'A',
      planeCode: '',
    },
    config: { ...BASE_CONFIG, width: 380, lang: 'EN' },
    passengers: [
      { id: 'p1', passengerLabel: 'John Smith', passengerColor: '#e91e63' },
      { id: 'p2', passengerLabel: 'Mary Johnson', passengerColor: '#2196f3' },
    ],
  },
  {
    key: 'qt777',
    label: 'QT777 · DXB → LHR',
    route: 'Dubai → London',
    date: '21 Sep 2026',
    flight: {
      id: 'demo',
      airlineCode: 'QT',
      flightNo: '777',
      departureDate: '2026-09-21',
      departure: 'DXB',
      arrival: 'LHR',
      cabinClass: 'A',
      planeCode: '',
    },
    config: { ...BASE_CONFIG, width: 400, lang: 'EN' },
    passengers: [
      { id: 'p1', passengerLabel: 'Alice Brown', passengerColor: '#9c27b0' },
      { id: 'p2', passengerLabel: 'Bob White', passengerColor: '#ff9800' },
      { id: 'p3', passengerLabel: 'Carol Lee', passengerColor: '#4caf50' },
    ],
  },
  {
    key: 'dl898',
    label: 'DL898 · ATL → LAX',
    route: 'Atlanta → Los Angeles',
    date: '21 Sep 2026',
    flight: {
      id: 'dl898',
      airlineCode: 'DL',
      flightNo: '898',
      departureDate: '2026-09-21',
      departure: 'ATL',
      arrival: 'LAX',
      cabinClass: 'A',
      planeCode: '',
    },
    config: { ...BASE_CONFIG, width: 360, lang: 'EN' },
    availability: [{ label: '*', price: 29, currency: 'USD' }],
    passengers: [{ id: 'p1', passengerLabel: 'Tom Davis', passengerColor: '#f44336' }],
  },
  {
    key: 'as1002',
    label: 'AS1002 · HNL → ITO',
    route: 'Honolulu → Hilo',
    date: '21 Sep 2026',
    flight: {
      id: 'as1002',
      airlineCode: 'AS',
      flightNo: '1002',
      departureDate: '2026-09-21',
      departure: 'HNL',
      arrival: 'ITO',
      cabinClass: 'A',
      planeCode: '',
    },
    config: { ...BASE_CONFIG, width: 350, lang: 'EN' },
  },
  {
    key: 'lh470',
    label: 'LH470 · FRA → YYZ',
    route: 'Frankfurt → Toronto',
    date: '21 Sep 2026',
    flight: {
      id: 'lh470',
      airlineCode: 'LH',
      flightNo: '470',
      departureDate: '2026-09-21',
      departure: 'FRA',
      arrival: 'YYZ',
      cabinClass: 'A',
      planeCode: '',
    },
    config: { ...BASE_CONFIG, width: 380, lang: 'DE' },
    passengers: [
      { id: 'p1', passengerLabel: 'Hans Müller', passengerColor: '#3f51b5' },
      { id: 'p2', passengerLabel: 'Maria Weber', passengerColor: '#009688' },
    ],
  },
];
